In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df_india = pd.read_excel(r'alldatasets.xlsx',sheet_name='India')

In [3]:
df_india.head()

,childid,country,height,stunting_2cat,EDUYRS2,z_score,timeschool,agegapr1,momeduyrsr1,chsexr1,agemonr1,hhsizer1,wi_newr1,job_cat,pvt_sector,earn,earn_usd
0,IN011004,India,164.000000,1.0,10.0,0.402029,10.0,13.0,0.0,1,95,4,0.458333,5,1,6000,98.376785
1,IN011006,India,158.199997,0.0,10.0,0.143023,30.0,12.0,0.0,0,95,4,0.097222,5,1,32000,524.676147
2,IN011012,India,157.199997,0.0,16.5,0.276244,10.0,5.0,10.0,0,101,6,0.722222,2,1,0,0.000000
3,IN011013,India,169.500000,0.0,11.0,0.252178,5.0,NaN,12.0,1,98,2,0.814815,5,1,9000,147.565170
4,IN011014,India,162.199997,0.0,7.0,0.394253,NaN,7.0,16.5,0,100,4,0.796296,2,1,72000,1180.521362

In [4]:
df_india.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536 entries, 0 to 535
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   childid        536 non-null    object
 1   country        536 non-null    object
 2   height         536 non-null    float64
 3   stunting_2cat  535 non-null    float64
 4   EDUYRS2        536 non-null    float64
 5   z_score        531 non-null    float64
 6   timeschool     457 non-null    float64
 7   agegapr1       504 non-null    float64
 8   momeduyrsr1    528 non-null    float64
 9   chsexr1        536 non-null    int64
 10  agemonr1       536 non-null    int64
 11  hhsizer1       536 non-null    int64
 12  wi_newr1       536 non-null    float64
 13  job_cat        536 non-null    int64
 14  pvt_sector     536 non-null    int64
 15  earn           536 non-null    int64
 16  earn_usd       536 non-null    float64
dtypes: float64(9), int64(6), object(2)
memory usage: 71.3+ KB

In [5]:
df_india.describe()

,height,stunting_2cat,EDUYRS2,z_score,timeschool,agegapr1,momeduyrsr1,chsexr1,agemonr1,hhsizer1,wi_newr1,job_cat,pvt_sector,earn,earn_usd
count,536.000000,535.000000,536.000000,531.000000,457.000000,504.000000,528.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.0,5.360000e+02,536.000000
mean,160.503918,0.358879,10.619869,-0.196304,17.663020,6.519841,1.241477,0.606343,95.776119,5.651119,0.352789,3.440299,1.0,2.585754e+04,423.963555
std,10.020669,0.480120,3.713290,0.955242,19.307195,3.171632,2.936055,0.489017,3.827382,2.111720,0.189299,1.893466,0.0,1.586158e+05,2600.685295
min,106.500000,0.000000,0.000000,-3.822028,0.000000,0.000000,0.000000,0.000000,87.000000,2.000000,0.006944,1.000000,1.0,0.000000e+00,0.000000
25%,152.775002,0.000000,9.000000,-0.843443,5.000000,5.000000,0.000000,0.000000,92.000000,4.000000,0.188889,1.000000,1.0,2.725000e+03,44.679455
50%,161.800003,0.000000,10.250000,-0.188679,10.000000,5.000000,0.000000,1.000000,97.000000,5.000000,0.340278,5.000000,1.0,1.000000e+04,163.961304
75%,168.000000,1.000000,12.000000,0.480237,30.000000,8.000000,0.000000,1.000000,99.000000,6.000000,0.470238,5.000000,1.0,2.400000e+04,393.507141
max,184.500000,1.000000,20.500000,2.816349,180.000000,26.000000,16.500000,1.000000,101.000000,24.000000,0.879630,6.000000,1.0,3.600000e+06,59026.070310

In [6]:
df_india=df_india.astype({"chsexr1": 'object', "job_cat": 'object', "pvt_sector": 'object',"stunting_2cat": 'object'})

In [7]:
df_india.dtypes

childid           object
country           object
height           float64
stunting_2cat     object
EDUYRS2          float64
z_score          float64
timeschool       float64
agegapr1         float64
momeduyrsr1      float64
chsexr1           object
agemonr1           int64
hhsizer1           int64
wi_newr1         float64
job_cat           object
pvt_sector        object
earn               int64
earn_usd         float64
dtype: object

In [8]:
df_outlier=df_india.copy()

In [9]:
df_outlier.dtypes

childid           object
country           object
height           float64
stunting_2cat     object
EDUYRS2          float64
z_score          float64
timeschool       float64
agegapr1         float64
momeduyrsr1      float64
chsexr1           object
agemonr1           int64
hhsizer1           int64
wi_newr1         float64
job_cat           object
pvt_sector        object
earn               int64
earn_usd         float64
dtype: object

In [10]:
total = df_outlier.isnull().sum().sort_values(ascending=False)
percent = (df_outlier.isnull().sum()/df_outlier.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Missing Percent'])
missing_data['Missing Percent'] = missing_data['Missing Percent'].apply(lambda x: x * 100)
missing_data.loc[missing_data['Missing Percent'] > 95]

Empty DataFrame
Columns: [Total, Missing Percent]
Index: []

In [11]:
df_outlier=df_outlier.select_dtypes(include=['int64','floating'])

In [12]:
df_outlier.dtypes

height         float64
EDUYRS2        float64
z_score        float64
timeschool     float64
agegapr1       float64
momeduyrsr1    float64
agemonr1         int64
hhsizer1         int64
wi_newr1       float64
earn             int64
earn_usd       float64
dtype: object

In [13]:
import warnings

warnings.filterwarnings('ignore')

In [14]:
df_outlier.dtypes

height         float64
EDUYRS2        float64
z_score        float64
timeschool     float64
agegapr1       float64
momeduyrsr1    float64
agemonr1         int64
hhsizer1         int64
wi_newr1       float64
earn             int64
earn_usd       float64
dtype: object

In [15]:
#sns.pairplot(df_outlier)

# Outlier Cappping

In [16]:
def cap_data(df):
    for col in df.columns:
        print("capping the ",col)
        if (((df[col].dtype)=='float64') | ((df[col].dtype)=='int64') | ((df[col].dtype)=='float32')):
            percentiles = df[col].quantile([0.01,0.99]).values
            df[col][df[col] <= percentiles[0]] = percentiles[0]
            df[col][df[col] >= percentiles[1]] = percentiles[1]
        else:
            df[col]=df[col]
    return df

In [17]:
final_df=cap_data(df_outlier)

capping the  height
capping the  EDUYRS2
capping the  z_score
capping the  timeschool
capping the  agegapr1
capping the  momeduyrsr1
capping the  agemonr1
capping the  hhsizer1
capping the  wi_newr1
capping the  earn
capping the  earn_usd

In [18]:
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler

In [19]:
df_india=df_india.drop(['childid','country'],axis=1)

In [20]:
all_category_features=df_india.select_dtypes(include='object')

In [21]:
all_category_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536 entries, 0 to 535
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   stunting_2cat  535 non-null    object
 1   chsexr1        536 non-null    object
 2   job_cat        536 non-null    object
 3   pvt_sector     536 non-null    object
dtypes: object(4)
memory usage: 16.9+ KB

# KNN for Categories

In [22]:
mm = MinMaxScaler()

def find_category_mappings(df, variable):
    return {k: i for i, k in enumerate(df[variable].dropna().unique(), 0)}

def integer_encode(df , variable, ordinal_mapping):
    df[variable] = df[variable].map(ordinal_mapping)

mappin = dict()
def imputation(df1 , cols):
    df = df1.copy()
    #Encoding dict &amp; Removing nan    
    #mappin = dict()
    for variable in cols:
        mappings = find_category_mappings(df, variable)
        mappin[variable] = mappings

    #Apply mapping
    for variable in cols:
        integer_encode(df, variable, mappin[variable])  

    #Minmaxscaler and KNN imputation 
    sca = mm.fit_transform(df)
    knn_imputer = KNNImputer()
    knn = knn_imputer.fit_transform(sca)
    df.iloc[:,:] = mm.inverse_transform(knn)
    for i in df.columns : 
        df[i] = round(df[i]).astype('int')

    #Inverse transform
    for i in cols:
        inv_map = {v: k for k, v in mappin[i].items()}
        df[i] = df[i].map(inv_map)
    return df

In [23]:
df_cat_imp=imputation(all_category_features,['stunting_2cat','chsexr1','job_cat','pvt_sector'])

In [24]:
df_cat_imp.isnull().sum().sort_values(ascending = False)

pvt_sector       0
job_cat          0
chsexr1          0
stunting_2cat    0
dtype: int64

In [25]:
df_cat_imp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536 entries, 0 to 535
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   stunting_2cat  536 non-null    float64
 1   chsexr1        536 non-null    int64
 2   job_cat        536 non-null    int64
 3   pvt_sector     536 non-null    int64
dtypes: float64(1), int64(3)
memory usage: 16.9 KB

In [26]:
#df_cat_imp.to_csv(r'C:\Users\rramr\OneDrive\Desktop\Modern Scientist Global\Peru\df_knn_before.csv', encoding='utf-8', index=True)

In [27]:
#all_category_features=df_et.select_dtypes(include='o')

In [28]:
#cat_dummies = pd.get_dummies(all_category_features, dummy_na=True)
#cat_dummies.head()

# KNN for numerics

In [29]:
df_knn=final_df.copy()

In [30]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5)
df_num_imp = pd.DataFrame(imputer.fit_transform(df_knn),columns = df_knn.columns)

In [31]:
df_num_imp.head()

,height,EDUYRS2,z_score,timeschool,agegapr1,momeduyrsr1,agemonr1,hhsizer1,wi_newr1,earn,earn_usd
0,164.000000,10.0,0.402029,10.0,13.0,0.0,95.0,4.0,0.458333,6000.0,98.376785
1,158.199997,10.0,0.143023,30.0,12.0,0.0,95.0,4.0,0.097222,32000.0,524.676147
2,157.199997,16.5,0.276244,10.0,5.0,10.0,101.0,6.0,0.722222,0.0,0.000000
3,169.500000,11.0,0.252178,5.0,9.2,12.0,98.0,3.0,0.786204,9000.0,147.565170
4,162.199997,7.0,0.394253,11.4,7.0,12.0,100.0,4.0,0.786204,72000.0,1180.521362

In [32]:
df_outlier_concat = pd.concat([df_num_imp, df_cat_imp], axis=1)
df_outlier_concat.head()

,height,EDUYRS2,z_score,timeschool,agegapr1,momeduyrsr1,agemonr1,hhsizer1,wi_newr1,earn,earn_usd,stunting_2cat,chsexr1,job_cat,pvt_sector
0,164.000000,10.0,0.402029,10.0,13.0,0.0,95.0,4.0,0.458333,6000.0,98.376785,1.0,1,5,1
1,158.199997,10.0,0.143023,30.0,12.0,0.0,95.0,4.0,0.097222,32000.0,524.676147,0.0,0,5,1
2,157.199997,16.5,0.276244,10.0,5.0,10.0,101.0,6.0,0.722222,0.0,0.000000,0.0,0,2,1
3,169.500000,11.0,0.252178,5.0,9.2,12.0,98.0,3.0,0.786204,9000.0,147.565170,0.0,1,5,1
4,162.199997,7.0,0.394253,11.4,7.0,12.0,100.0,4.0,0.786204,72000.0,1180.521362,0.0,0,2,1

In [33]:
df_outlier_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536 entries, 0 to 535
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   height         536 non-null    float64
 1   EDUYRS2        536 non-null    float64
 2   z_score        536 non-null    float64
 3   timeschool     536 non-null    float64
 4   agegapr1       536 non-null    float64
 5   momeduyrsr1    536 non-null    float64
 6   agemonr1       536 non-null    float64
 7   hhsizer1       536 non-null    float64
 8   wi_newr1       536 non-null    float64
 9   earn           536 non-null    float64
 10  earn_usd       536 non-null    float64
 11  stunting_2cat  536 non-null    float64
 12  chsexr1        536 non-null    int64
 13  job_cat        536 non-null    int64
 14  pvt_sector     536 non-null    int64
dtypes: float64(12), int64(3)
memory usage: 62.9 KB

In [34]:
df_outlier_concat=df_outlier_concat.astype({"stunting_2cat": 'int64'})

In [35]:
df_outlier_concat.head()

,height,EDUYRS2,z_score,timeschool,agegapr1,momeduyrsr1,agemonr1,hhsizer1,wi_newr1,earn,earn_usd,stunting_2cat,chsexr1,job_cat,pvt_sector
0,164.000000,10.0,0.402029,10.0,13.0,0.0,95.0,4.0,0.458333,6000.0,98.376785,1,1,5,1
1,158.199997,10.0,0.143023,30.0,12.0,0.0,95.0,4.0,0.097222,32000.0,524.676147,0,0,5,1
2,157.199997,16.5,0.276244,10.0,5.0,10.0,101.0,6.0,0.722222,0.0,0.000000,0,0,2,1
3,169.500000,11.0,0.252178,5.0,9.2,12.0,98.0,3.0,0.786204,9000.0,147.565170,0,1,5,1
4,162.199997,7.0,0.394253,11.4,7.0,12.0,100.0,4.0,0.786204,72000.0,1180.521362,0,0,2,1

In [36]:
df_knn_imp=df_outlier_concat.copy()

In [37]:
import statsmodels.api as sm

# cognition

In [38]:
#cognition

X = df_knn_imp["stunting_2cat"] ## X usually means our input variables (or independent variables)
y = df_knn_imp["z_score"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                z_score   R-squared:                       0.012
Model:                            OLS   Adj. R-squared:                  0.010
Method:                 Least Squares   F-statistic:                     6.467
Date:                Thu, 13 May 2021   Prob (F-statistic):             0.0113
Time:                        11:17:11   Log-Likelihood:                -717.40
No. Observations:                 536   AIC:                             1439.
Df Residuals:                     534   BIC:                             1447.
Df Model:                           1
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            -0.1235      0.050     -2.478      0.014      -0.221      -0.026
stunting_2cat    -0.2118      0.083     -2.543      0.011      -0.375      -0.048
==============================================================================
Omnibus:                        4.423   Durbin-Watson:                   1.677
Prob(Omnibus):                  0.110   Jarque-Bera (JB):                3.421
Skew:                          -0.070   Prob(JB):                        0.181
Kurtosis:                       2.635   Cond. No.                         2.42
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# height

In [39]:
#Height

X = df_knn_imp["stunting_2cat"] ## X usually means our input variables (or independent variables)
y = df_knn_imp["height"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 height   R-squared:                       0.041
Model:                            OLS   Adj. R-squared:                  0.039
Method:                 Least Squares   F-statistic:                     22.59
Date:                Thu, 13 May 2021   Prob (F-statistic):           2.58e-06
Time:                        11:17:11   Log-Likelihood:                -1965.9
No. Observations:                 536   AIC:                             3936.
Df Residuals:                     534   BIC:                             3944.
Df Model:                           1
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const           162.0141      0.512    316.512      0.000     161.009     163.020
stunting_2cat    -4.0651      0.855     -4.753      0.000      -5.745      -2.385
==============================================================================
Omnibus:                       48.168   Durbin-Watson:                   1.973
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               22.539
Skew:                          -0.311   Prob(JB):                     1.28e-05
Kurtosis:                       2.211   Cond. No.                         2.42
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# education

In [40]:
#education

X = df_knn_imp["stunting_2cat"] ## X usually means our input variables (or independent variables)
y = df_knn_imp["EDUYRS2"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                EDUYRS2   R-squared:                       0.002
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                    0.9533
Date:                Thu, 13 May 2021   Prob (F-statistic):              0.329
Time:                        11:17:11   Log-Likelihood:                -1452.6
No. Observations:                 536   AIC:                             2909.
Df Residuals:                     534   BIC:                             2918.
Df Model:                           1
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            10.7304      0.196     54.621      0.000      10.344      11.116
stunting_2cat    -0.3205      0.328     -0.976      0.329      -0.965       0.324
==============================================================================
Omnibus:                        0.583   Durbin-Watson:                   1.852
Prob(Omnibus):                  0.747   Jarque-Bera (JB):                0.642
Skew:                          -0.077   Prob(JB):                        0.725
Kurtosis:                       2.929   Cond. No.                         2.42
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# cognition covariates

In [41]:
X = df_knn_imp[["stunting_2cat",'agemonr1','chsexr1','agegapr1','momeduyrsr1','hhsizer1','wi_newr1']] ## X usually means our input variables (or independent variables)
y = df_knn_imp["z_score"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                z_score   R-squared:                       0.234
Model:                            OLS   Adj. R-squared:                  0.224
Method:                 Least Squares   F-statistic:                     23.04
Date:                Thu, 13 May 2021   Prob (F-statistic):           2.61e-27
Time:                        11:17:11   Log-Likelihood:                -649.19
No. Observations:                 536   AIC:                             1314.
Df Residuals:                     528   BIC:                             1349.
Df Model:                           7
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            -0.3911      0.903     -0.433      0.665      -2.166       1.383
stunting_2cat    -0.1557      0.074     -2.104      0.036      -0.301      -0.010
agemonr1         -0.0027      0.009     -0.296      0.768      -0.021       0.016
chsexr1           0.4621      0.073      6.337      0.000       0.319       0.605
agegapr1         -0.0088      0.012     -0.708      0.479      -0.033       0.016
momeduyrsr1       0.0930      0.014      6.581      0.000       0.065       0.121
hhsizer1         -0.0181      0.018     -0.980      0.327      -0.054       0.018
wi_newr1          0.7868      0.209      3.764      0.000       0.376       1.198
==============================================================================
Omnibus:                       10.048   Durbin-Watson:                   1.793
Prob(Omnibus):                  0.007   Jarque-Bera (JB):                6.776
Skew:                          -0.133   Prob(JB):                       0.0338
Kurtosis:                       2.518   Cond. No.                     2.46e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.46e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# Height covariates

In [42]:
X = df_knn_imp[["stunting_2cat",'agemonr1','chsexr1','agegapr1','momeduyrsr1','hhsizer1','wi_newr1']] ## X usually means our input variables (or independent variables)
y = df_knn_imp["height"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 height   R-squared:                       0.666
Model:                            OLS   Adj. R-squared:                  0.661
Method:                 Least Squares   F-statistic:                     150.3
Date:                Thu, 13 May 2021   Prob (F-statistic):          2.59e-121
Time:                        11:17:11   Log-Likelihood:                -1683.2
No. Observations:                 536   AIC:                             3382.
Df Residuals:                     528   BIC:                             3417.
Df Model:                           7
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const           140.6465      6.218     22.619      0.000     128.431     152.862
stunting_2cat    -3.9334      0.509     -7.724      0.000      -4.934      -2.933
agemonr1          0.1064      0.064      1.664      0.097      -0.019       0.232
chsexr1          15.0720      0.502     30.030      0.000      14.086      16.058
agegapr1         -0.1479      0.085     -1.738      0.083      -0.315       0.019
momeduyrsr1       0.3013      0.097      3.096      0.002       0.110       0.492
hhsizer1          0.1896      0.127      1.492      0.136      -0.060       0.439
wi_newr1          4.3089      1.439      2.994      0.003       1.482       7.136
==============================================================================
Omnibus:                       10.372   Durbin-Watson:                   2.013
Prob(Omnibus):                  0.006   Jarque-Bera (JB):               11.393
Skew:                          -0.263   Prob(JB):                      0.00336
Kurtosis:                       3.482   Cond. No.                     2.46e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.46e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# education covariates

In [43]:
X = df_knn_imp[["stunting_2cat",'agemonr1','chsexr1','agegapr1','momeduyrsr1','hhsizer1','wi_newr1']] ## X usually means our input variables (or independent variables)
y = df_knn_imp["EDUYRS2"] ## Y usually means our output/dependent variable
X = sm.add_constant(X) ## let's add an intercept (beta_0) to our model
# Note the difference in argument order
model = sm.OLS(y, X,missing='drop').fit() ## sm.OLS(output, input)
predictions = model.predict(X)

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                EDUYRS2   R-squared:                       0.111
Model:                            OLS   Adj. R-squared:                  0.099
Method:                 Least Squares   F-statistic:                     9.413
Date:                Thu, 13 May 2021   Prob (F-statistic):           5.04e-11
Time:                        11:17:12   Log-Likelihood:                -1421.5
No. Observations:                 536   AIC:                             2859.
Df Residuals:                     528   BIC:                             2893.
Df Model:                           7
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const             8.3161      3.816      2.179      0.030       0.819      15.813
stunting_2cat    -0.1546      0.313     -0.494      0.621      -0.769       0.459
agemonr1      -7.762e-05      0.039     -0.002      0.998      -0.077       0.077
chsexr1           0.8892      0.308      2.887      0.004       0.284       1.494
agegapr1          0.0421      0.052      0.806      0.421      -0.061       0.145
momeduyrsr1       0.2554      0.060      4.277      0.000       0.138       0.373
hhsizer1          0.0358      0.078      0.459      0.646      -0.117       0.189
wi_newr1          2.9496      0.883      3.340      0.001       1.215       4.685
==============================================================================
Omnibus:                        0.160   Durbin-Watson:                   1.869
Prob(Omnibus):                  0.923   Jarque-Bera (JB):                0.063
Skew:                           0.007   Prob(JB):                        0.969
Kurtosis:                       3.051   Cond. No.                     2.46e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.46e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""